apiVersion: 1
  datasources:
    - name: Elasticsearch
      type: elasticsearch
      url: http://elasticsearch:9200
    - name: Prometheus
      type: jaeger 
      url: http://prometheus:9090
    - name: Jaeger 
      type: jaeger 
      url: http://jaeger:16686
    - name: OrderDB 
      type: postgresql
      url: http://orderdb:5432/defaultorders
    - name: KitchenRecipeDB
      type: postgresql
      url: http://kitchenrecipedb:5432/kitchenrecipes
    - name: BaristaRecipeDB
      type: postgresql
      url: http://baristarecipedb:5432/baristarecipes
