version: '3.2'

services:
  orderservice:
    container_name: orderservice
    image: sbaeker/order-service:latest
    ports:
      - "8080:8080"
    networks:
      - coffeeshop

  productservice:
    container_name: productservice
    image: sbaeker/product-service:latest
    ports:
      - "8081:8081"
    networks:
      - coffeeshop
    depends_on:
      - rabbitmq

  kitchenservice:
    container_name: kitchenservice
    image: sbaeker/kitchen-service:latest
    ports:
      - "8082:8082"
    networks:
      - coffeeshop
    depends_on:
      - rabbitmq

  baristaservice:
    container_name: baristaservice
    image: sbaeker/barista-service:latest
    ports:
      - "8083:8083"
    networks:
      - coffeeshop
    depends_on:
      - rabbitmq

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - coffeeshop

networks:
  coffeeshop:
    driver: bridge
