version: '3.2'

services:
  elasticsearch:
    image: docker.io/elastic/elasticsearch:7.16.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"
    networks:
      - coffeeshop

  fluentd:
    build:
      context: fluentd
      dockerfile: Dockerfile
    ports:
      - "12201:12201/udp"
    volumes:
      - ./fluentd/config/:/fluentd/etc
    networks:
      - coffeeshop
    depends_on:
      - elasticsearch

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - coffeeshop

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    command: --config.file=/prometheus/config/prometheus.yml
    networks:
      - coffeeshop

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - coffeeshop

networks:
  coffeeshop:
    driver: bridge
