version: '3.2'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - coffeeshop
    env_file:
      - .env
networks:
  coffeeshop:
    driver: bridge